### ISSUE TITLE
Error when attempting to use US Census Airbyte Source

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#196]
When running `flowctl discover`, Flow throws the following error:

flow@docker-desktop:/workspace$ flowctl discover --image=airbyte/source-us-census

Creating a connector configuration stub at /workspace/discover-source-us-census.config.yaml.
Edit and update this file, and then run this command again.
schema.yaml error at <root> :
failed to build JSON schema

Caused by:
    0: at keyword 'pattern' of schema 'file:///var/tmp/flow-discover481589645/schema.yaml#/properties/query_params': failed to parse regex: regex parse error:
           ^\w+=[\w,:*]+(&(?!key)\w+=[\w,:*]+)*$
                          ^^^
       error: look-around, including look-ahead and look-behind, is not supported
    1: failed to parse regex: regex parse error:
           ^\w+=[\w,:*]+(&(?!key)\w+=[\w,:*]+)*$
                          ^^^
       error: look-around, including look-ahead and look-behind, is not supported
    2: regex parse error:
           ^\w+=[\w,:*]+(&(?!key)\w+=[\w,:*]+)*$
                          ^^^
       error: look-around, including look-ahead and look-behind, is not supported
schema.yaml error at <root> :
referenced schema fragment location file:///var/tmp/flow-discover481589645/schema.yaml does not exist
FATA[0004] fatal error                                   err="parsing JSON schema spec: 2 build errors"

**Comment by psFried** [comment]
The cause of this error is just that the regex patterns used in that connector's json schema use features that the rust `regex` crate doesn't support. That's not entirely surprising, given that many other popular regex engines have also dropped support for look-behind in order to guarantee reasonable performance. The [fancy-regex](https://crates.io/crates/fancy-regex) crate documentation explains the performance situation well. 

Nevertheless, the [JSON Schema docs](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html) specify the [ECMA-262](https://www.ecma-international.org/publications/standards/Ecma-262.htm) standard, which includes support for look-behind, and they also specifically mention look-around patterns being included in the "safe subset" of regex features. So I think this is a general gap in our JSON schema implementation, and I think the solution here is to use the fancy-regex crate.
