### ISSUE TITLE
Flow capture perfomance investigation

### ISSUE THREAD

**Issue by psFried** [estuary/flow#220]
We've seen anecdotal evidence of pretty high latency for capturing data and materializing it. It sometimes takes a minute or two for data to show up in the materialization endpoint. It seems like something is wrong with that. Of course we don't really have a great understanding of what the performance _should_ be, so it's hard to articulate a specific desired outcome from this issue. But I think the goal at this stage is to gain at least a basic understanding of what's going on, and formulate an opinion on what the next steps should be. Of course opportunistically fixing things is very much on the table, but so is filing new issues to address a bit later.

**Comment by jgraettinger** [comment]
> It sometimes takes a minute or two for data to show up in the materialization endpoint

It's actually expected that it would take precisely two minutes for a really high-volume capture to start appearing in a materialization.

That's because the capture runs in a transaction with a maximum upper bound of 1 min (as currently configured), and the consumers framework will greedily include more ready documents into a single transaction. Same story with the materialization (adding another minute). This can be tuned through the ( currently hard-coded) [MaxTxnDuration](https://github.com/estuary/flow/blob/master/go/flowctl/cmd-apply.go#L282)

**Comment by jgraettinger** [comment]
>  it's hard to articulate a specific desired outcome from this issue

Proposal:
 * Establish a repeatable and representative benchmark (citi-bike data seems fine to me).
 * Work out a process / instrumentation for getting a macro-to-micro understanding of where we're spending time.
    - Timing instrumentation ? Open tracing spans ? Go profiling tools ?
    - Having some always-on instrumentation would be 👌👌👌

IMO this is more about setting up a process for measuring, evaluating, and diagnosing performance.

**Comment by jgraettinger** [comment]
We've spent a lot of time with this and have a much clearer picture of performance characteristics.
