### ISSUE TITLE
Proposal: Introduce `flowctl logs` Command

### ISSUE THREAD

**Issue by saterus** [estuary/flow#298]
It's much easier to debug problems now that task logs are being written to journals. However, accessing those logs requires reasonable familiarity with the underlying Gazette concepts and CLI commands.

To view a task's logs right now:

1. `flowctl journals list`
2. `flowctl journals read -l name=ops/acmeCo/logs/kind=capture/name=acmeCo%2Ffirehose/pivot=00`

This is cumbersome and not very obvious or easily discovered by a new user.

I propose that we add a new `flowctl logs` command. This command could read the logs journal for a task via the existing mechanisms for reading journals, but expose a more intuitive interface for doing so.

1. `flowctl logs acmeCo/firehose`

I think we should allow a user to specify the name of the task as it would appear in their catalog yaml. Eg. `/acmeCo/firehose`, rather than `ops/acmeCo/logs/kind=capture/name=acmeCo%2Ffirehose/pivot=00`. Given that all our logs are structured as `ops/:tenant:/logs/kind=:tasktype:/name=:taskname:` and task names are unique across task type, I believe we should be able to figure out which log to read from without needing to have the user specify everything explicitly.

We could expose options for specifying `--tail`, for `--offsets`, and for `--partition` ranges, each with sensible defaults.

## Further Enhancements

It would also be helpful to easily set the log level on a task/shard. While the shard spec holds the log level, it suffers from the same workflow issues as reading the logs. New users certainly won't think to edit the shard (if they know what a shard is) in order to change the logging level of the task.

## Alternatives

I've been using a set of shell functions for making reading from a journal a bit easier. These aren't very distributable to a new user, but are a useful stopgap in the meantime. These require https://github.com/lotabout/skim or some equivalent fuzzy finder to perform the interactive selection.

Fish:
```fish
function read_journal -a extra_args
    set -l journal (flowctl journals list -o json | jq ".journals[].spec.name" -cr | sk)
    if test -z $journal
        echo "No journal given"
        return
    end
    flowctl journals read -l name=$journal $extra_args
end
```

Bash (translated untested from Fish):
```bash
function read_journal() {
    journal=$(flowctl journals list -o json | jq ".journals[].spec.name" -cr | sk)
    if test -z $journal; then
        echo "No journal given"
        return
    fi
    flowctl journals read -l name=$journal $@
}
```

**Comment by psFried** [comment]
I fully agree that viewing logs should feel pretty easy for users, and `journals read` is too low-level to be user-friendly here. For reference, here's another way of writing that `journals read` command that uses label selectors to grab the right journal:

```
flowctl journals read -l estuary.dev/collection=ops/myTenant/logs -l estuary.dev/field/name=myTenant/my/task
```

I don't know if I'm necessarily sold on `flowctl logs` just yet, because there's a lot of conceptual overlap between that and another sub-command that I think we might also want. The other sub-command I'm considering is something like:

```
flowctl collections read <collection-name> [--partition <name>=<value>]
```

Using that to read logs for a particular task would look like:

```
flowctl collections read ops/myTenant/logs --partition name=myTenant/my/capture
```

This is definitely not as nice as `flowctl logs` when you're starting from the position of just wanting logs. But it is still a bit better than the equivalent `journals read` command since you don't have to remember the label names. Other differences would be that `collections read` (or `logs` for that matter) would use a [sequencer](https://github.com/gazette/core/blob/master/message/sequencer.go#L36) internally, would filter out any `"ack": true` documents, and would perhaps be more opinionated about `--broker.cache.size`.

So the question on my mind is, if we had a `collections read`, would we still want `logs`? Of course that begs the question of whether `collections read` is even something we should have. I think it seems useful, but there I'd like to get @jgraettinger 's take on things, because I'm not 100% certain of the implications of bringing a sequencer into the CLI, but it seems like a reasonable subcommand to me.

Even if we had `collections read`, I could still see an argument for also having `logs`, since it's perhaps more discoverable. But on the other hand, it'd be nice to reinforce the idea that logs are just Flow collections and can be consumed in the same way as any other, since it may encourage users to setup derivations and materializations of logs instead of trying to shell out to `flowctl` all the time.

Sorry for the ramble. Curious to get your thoughts on that.

**Comment by jgraettinger** [comment]
I'm following the discussion but don't have much to add. We definitely need something here. `flowctl logs` is better for meeting a user at their current need. `flowctl collections read` is better from an API DRY standpoint. 🤷 

Other Q's I don't know the A's to:
* If `flowctl journals read` offered a read-committed mode, would we still want `flowctl collections read` ?
* Would there be other subcommands under `flowctl collections` ?
* If `journals read` supported read-committed mode, then could `flowctl logs` and `flowctl collections read` both be simple and explanatory wrappers which clearly (to the user) delegate to `flowctl journals read` with a corresponding label selector ?

**Comment by psFried** [comment]
I really like the idea of adding a read-committed mode to `journals read`, and then having other commands (`logs` and `collections read`) as aliases with easier CLI flags. One nice thing is that we wouldn't actually need to add a read-committed mode in order to implement `logs` as an alias. We could implement that today, since logs are all `PublishCommitted`.

There's a few other things I'm curious about, just to build a better understanding of a read-committed mode. My understanding is that a generic read-committed mode for `journals read` would still output all of the `"ack": true` documents. Is that correct? Is filtering out those acknowledgements something that `journals read` could be taught to do generically based on the flags in the uuid? This is, AFAIK, completely unnecessary for reading logs, since logs are published using `PublishCommitted`, and don't have acks. But it seems like it could be useful in other aliases.

**Comment by saterus** [comment]
> So the question on my mind is, if we had a `collections read`, would we still want `logs`? [...] Even if we had collections read, I could still see an argument for also having logs, since it's perhaps more discoverable. 

Yeah, I think you nailed it with your followup. When I wrote this up, I honestly didn't think of `logs` as anything other than a shortcut for the existing `journals read` command with better user experience. I think there's opportunity for tailoring specific enhancements to _logs in particular_ (formatting, filtering, etc), but I don't think we need to build any of that right now.

> It'd be nice to reinforce the idea that logs are just Flow collections and can be consumed in the same way as any other, since it may encourage users to setup derivations and materializations of logs instead of trying to shell out to flowctl all the time.

I don't think we should _hide_ from users the fact that we store logs as collections, but I don't think it's something that we need to force upon them when they are first learning the system. Logs are a way to introspect what's happening when you otherwise don't fully understand the system, so making that an easy on-ramp is worthwhile. I certainly don't want to force a user to figure out how to write a derivation and setup a database to dump their logs to before they can view them. That's potentially a super valuable thing for them to do _eventually_, but not when doing quick debugging or learning the system. 

> The last question is pondering whether we might want many aliases of this kind that are targeted at specific use cases, but where running the alias makes it clear that everything is "just" a journal read and there's no magic, while also taking advantage of a teachable moment to explain journal label conventions to the user.

I think the term "alias" is a bit ambiguous here. I think they would be aliases only in the mechanics of how they work, not in how they are used by a user. I'm thinking of how everyday git subcommands are all created from the same building blocks, that while a user can technically also run, compose into useful high-level workflows.

In any case, explaining how the commands work with our building blocks in the docs seems like a good way to do this. I don't think I'd want to have these be literal text expansion aliases like bash. I wouldn't want to type `flowctl help`, see there is a `logs` subcommand, and then have `flowctl help logs` simply tell me that I should use `journals read` instead. I think this would miss a lot of the usefulness of tailoring better defaults/flags for specific purposes.

**Comment by psFried** [comment]
> I think the term "alias" is a bit ambiguous here.

Yeah, fair. I think for our purposes, I'd propose that these "aliases" are actually just regular CLI sub-commands that delegate to `journals read` somehow :wave: and simply explain them as aliases in the documentation and help.
