### ISSUE TITLE
connector stderr isn't included in error messages

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#301]
## Reproduction

Try running a flow catalog with a materialiation connector image that doesn't exist, or with a bad configuration, and get:
```
$ flowctl check --source end-to-end.flow.yaml
segment-events.flow.yaml error at /materializations/acmeCo~1webhook-callouts :
driver error while validating materialization acmeCo/webhook-callouts

Caused by:
    driver.Validate: connector failed: exit status 1
FATA[0000] fatal error                                   err="1 build errors"
```

I believe this is a regression introduced with the recent logging changes. Before, we intentionally buffered a chunk of stderr and included it as part of the returned error message, which is then plumbed through and presented as a user-facing error for why the catalog build failed.

/cc @psFried

**Comment by psFried** [comment]
Yeah, this is definitely a regression in the user experience for builds. I'm hesitant to simply revert to the prior behavior of taking a prefix of stderr as the error message, though, because it seems like a worse user experience at runtime. For example, when a capture encountered a parse error in a file, the stderr prefix that's returned as the error message is simply a duplication of lines that have already been logged, and it often doesn't contain anything that's actually pertinent to the error, since it had already logged `<prefix_length>` bytes of unrelated content.

So, just thinking out loud about some possible alternatives:
Perhaps a minimal solution could be to tweak the log levels for build-time connector operations to ensure that any plain stderr lines are always output. So you'd see some kinda generic error and then scroll up and see the connector's logs above. We could perhaps even add a "see prior log output" message to the error, but it still seems like it wouldn't be the best user experience.

Another idea would be to create a separate `ops.Logger` implementation that buffers logs scoped to each task. These could then be printed "on-demand" if an error occurs during the validate or apply for that task. So something like:

```
Connector: "<image>" has returned an error. Here's the logs from running Validate on task "<task> ":
<full JSON logs here>...
```

Continuing to riff on that, we could potentially just capture all build-time logs, with connector logs scoped to each task, and save them either as separate files, or else stuff them into the sqlite database, so that any build-related logs would remain available after the fact. We could then still output the logs right along with the generic error message in the case that a connector exits without outputting the expected response. I think this one is making sense to me as an ideal resolution to this issue. What do you think?

**Comment by jgraettinger** [comment]
> when a capture encountered a parse error in a file, the stderr prefix that's returned as the error message is simply a duplication of lines that have already been logged, and it often doesn't contain anything that's actually pertinent to the error, since it had already logged <prefix_length> bytes of unrelated content.

Well, as a practical matter (at least today), the user doesn't see those log lines because they're logged as info (below the default output level). Supposing they do see them, there's still utility in having them in the error because 1) the error is persisted in the build database and can be inspected there, presented in UI, etc, and 2) it tightly associates the stderr output with the specific error context and scope.

Here's the former implementation: https://github.com/estuary/flow/blob/0381c37a3647ba7c75c5ae9dea203be781429282/go/capture/driver/airbyte/connector.go#L377-L390 We could have it instead use a ring buffer, and track the suffix of bytes. I recall thinking about that and shrugging, as connectors don't log that much in practice, and we hadn't seen any case where that behavior didn't feel reasonable.

This could probably be trivially fixed by bringing back that `connectorStderr` and having it wrap the log forwarder.
