### ISSUE TITLE
maybe: support individual schemas with > 64 properties

### ISSUE THREAD

**Issue by jgraettinger** [estuary/flow#315]
To make schema validation fast, we use an intern table strategy where we track observed properties using assigned bits in a 64-bit word. Then we can compare against required properties of a schema using a bitmask. The intern table is specific to a single JSON schema, and different schemas, or in-place sibling applications of a common parent schema, use separate intern tables which can each be up to 64 items large.

We've seen some... _questionable_ schema documents from third-party connectors that produce schemas with significantly more than 64 properties. "questionable" because there's most certainly an element of garbage-in, garbage-out going on here, and it's not yet clear to me that it's _actually required_ to support larger schemas at this time, but... here's a tracking issue. 🤷

**Comment by mdibaiee** [comment]
One way to work around this is to wrap `allOf` around the JSONSchema when we are compiling it for our own code's usage. We need to do this ensuring that the JSONSchema passed to the connector stays intact because the code that handles the JSONSchema is usually not 100% compatible with spec and we see this kind of code commonly:

```
if x['type'] == 'object':
  props = x['properties']
```

This fails if we modify the JSONSchema below:

```
type: object
properties:
  name:
    type: string
```

To:

```
type: object
allOf:
  - properties:
      name:
        type: string
```

So we need to do this transparently.

**Comment by jgraettinger** [comment]
[Here is where](https://github.com/estuary/flow/blob/master/crates/json/src/schema/build.rs#L258-L266) we process the set of properties of a schema.

We can examine the size of this array, and if > 64 then process it into equal chunks < 64 which are handled as `App::AllOf` applications.
