### ISSUE TITLE
option to tail logs with flowctl

### ISSUE THREAD

**Issue by mdibaiee** [estuary/flow#759]
Today I wanted to check logs of a deployment and it took about 5 minutes for me to get to logs for today. An option to only read last N lines of a journal / logs would help a lot.

**Comment by psFried** [comment]
We don't yet have an option to output the last N lines, but I think you should be able to use the `--since 1d` option to limit the amount of data that needs to be fetched. It might still need to fetch more than the last 24h of data, since it has to start reading at the beginning of a fragment, but it should at least be able to avoid fetching any fragments that don't overlap the desired time period.

There's also a `--follow` option, which is basically equivalent to `tail --follow`.

We'll be able to do some more fine grained filtering once the Rust Gazette client is able to parse messages.

**Comment by mdibaiee** [comment]
@psFried I can't find `--since` option on `flowctl-go` or `flowctl-admin`, or `gazctl`:

```
[journals command options]

    Interact with broker journals:
          --zone=                                         Availability zone within which this process is running (default: local) [$ZONE]

    Logging:
          --log.level=[trace|debug|info|warn|error|fatal] Logging level (default: warn) [$LOG_LEVEL]
          --log.format=[json|text|color]                  Logging output format (default: text) [$LOG_FORMAT]

    Broker:
          --broker.address=                               Service address endpoint (default: http://localhost:8080) [$BROKER_ADDRESS]
          --broker.cache.size=                            Size of client route cache. If <= zero, no cache is used (server always proxies) (default: 0) [$BROKER_CACHE_SIZE]
          --broker.cache.ttl=                             Time-to-live of route cache entries. (default: 1m) [$BROKER_CACHE_TTL]

[read command options]
      -l, --selector=                                     Label selector of journals to read
      -b, --block                                         Do not exit on journal EOF; wait for new data until signaled
          --tail                                          Start reading from the journal write-head (rather than offset 0)
      -o, --output=                                       Output file path. Use '-' for stdout (default: -)
          --offsets=                                      Path from which initial journal offsets are read at startup
          --offsets-out=                                  Path to which final journal offsets are written at exit
          --file-root=                                    Filesystem path which roots file:// fragment store
```

The similar option `--offsets` is not human-friendly, I honestly don't know what is a valid input for that option even

**Comment by psFried** [comment]
Ah, the `--since` option is only on the new flowctl. It's kinda funny that your exact problem (taking a really long time to get logs) is what motivated me finally build the new flowctl logs subcommand. Anyway, if you just use the new flowctl for that, then you don't need to port forward anything, either, so it should go much faster for you. Please let me know if not.
