### ISSUE TITLE
Use values from default annotations when sending documents to materializations

### ISSUE THREAD

**Issue by williamhbaker** [estuary/flow#764]
When the combiner drains documents to send to a materialization, if a field doesn't exist the projection of that field will currently be a `null` value. We would like to take "default" annotations from the schema into account here, and instead project to the value of the "default" annotation if present & if the field doesn't exist in the document.

This will enable materializations from source documents which do not have every possible field explicitly present to be represented more usefully in a destination store, using the specified "default" value instead of `null`. A good example of this is the new ops catalog stats introduced in https://github.com/estuary/flow/pull/755. Ideally we would not need to publish documents with explicit 0's to avoid having `null` values in the materialization source.

Also as part of this, the build process should verify that the value supplied as a default validates against the allowable type for the field.

**Comment by mdibaiee** [comment]
This is interesting, why don't we apply this default value when we are capturing a document into the collection? Essentially, if we do this at materialization step, the document in the collection is going to be different from the one materialized, which is unintuitive to me 🤔

**Comment by williamhbaker** [comment]
There's maybe a small storage space benefit to not storing the document with the default values. A bigger benefit IMO is so that you can change default values on the schema a (re-)materialize existing documents and have those defaults expressed in the destination. I generally agree that it makes it less clear regarding looking at documents in the collection vs. what gets materialized, but on the other hand this is already a bit of a murky area with reduction annotations.

**Comment by mdibaiee** [comment]
> so that you can change default values on the schema a (re-)materialize existing documents and have those defaults expressed in the destination.

I'm not sure if this is always a benefit, specially if the details of how the default value is applied is not clear to the user (most of the time it isn't). I might expect that documents that have been consumed so far keep their existing default value while new ones use the newly specified default value.

**Comment by jgraettinger** [comment]
> This is interesting, why don't we apply this default value when we are capturing a document into the collection? Essentially, if we do this at materialization step, the document in the collection is going to be different from the one materialized, which is unintuitive to me 🤔

Think of this as an operation that exists only at the boundary of where projections are applied.

The schema can define default values for locations which are _not actually present_ in the document.
If a location isn't present, it can be assumed to have the default. So long as we're working with a JSON document there's no reason for us to materialize this default value in the location. In fact, that would break if the schema default were later changed -- our materialization into a capture document would be incorrect.

However, at the moment where we're _projecting_ a document into fields, we *must* take a position of what the value is. Projection doesn't have a way to represent a location which isn't actually present in the document.

In fact, we already apply a default today -- `null` -- which is the projected value of any document location that doesn't actually exist. In that sense, using the `default` annotation of the schema is a more-logically-consistent handling because there's no good reason why `null` is a sensible value here.
