### ISSUE TITLE
process & tooling for tenant stat migrations

### ISSUE THREAD

**Issue by psFried** [estuary/flow#842]
The goal is to have some process in place to handle updates to the ops catalog over time. The ops catalog is applied when creating a tenant via the betaOnboarding directive. After we make updates to the ops catalog sources, we'll minimally need some way to update the running catalog for each tenant. My inclination would normally be to try to limit the scope to only that, but in this case the boundaries of the scope aren't necessarily clear.

- When do we apply the new catalogs, and what triggers it?
- How should we handle a failure to apply the new catalog?
- Do we need to handle deletion of old ops catalog entities?

When the control-plane's database schema is changed (ex. add a column to the `tenants` table), it's not necessarily clear whether it's better to update existing tenant rows as part of that same DB migration, versus re-running parts of the (idempotent) tenant creation behavior from the betaOnboarding directive, versus having some other code-based migration.

When the ops catalog itself changes, it's pretty clear that we'd need some code to run. We wouldn't want to try updating the ops catalog as part of a normal db migration. So how I'm thinking about this is that, at least right now, there really isn't a generic one-size-fits-all solution for every change we might introduce.

The motivating example is adding counts of errors and warnings to the catalog stats table. Here's a first take at the process.

- Apply a DB migration to the control-plane database that adds the `error_count` and `warning_count` columns to the stats tables
- On agent startup, identify all tenants having an ops catalog that is less recent than the current version. For each tenant requiring migration:
  - Disable the existing stats materialization
  - Delete the materialization spec from `flow_materializations_v1`
  - Trigger the behavior to apply the ops catalog for that tenant (which implicitly re-enables the materialization)
  - Wait for publish to complete
    - If publish fails, then agent should exit non-zero and tell an adult.
  - Mark tenant as migrated

Those steps steps that run for each tenant, are actually _kind of_ particular to this specific case where we're updating the columns of the materialized table. If we instead considered an update to, say, just the derivation code, then we wouldn't need to disable the materialization or delete the spec. So in terms of the factoring in the `agent` crate, I think it makes sense to essentially treat each version bump as having its own associated migration function. So we'd put all those steps under something like `fn migrate_tenant_to_version_1(...)`. I think we should stop short of making this _too_ generic right now, though. I specifically don't think we should yet take a position on what the _next_ migration function should look like. For example, you might be thinking that the next change to the ops catalog might involve creating a `fn migrate_tenant_to_version_2(...)` that lives alongside the first version, or you might instead just rename the first function and assert that all tenants have _already_ been migrated to version 1 before attempting to migrate them to version 2. In other words, I'm not yet confident that I understand the desired behavior when an existing tenant is _multiple_ versions behind. Should we apply migration functions in order, only apply the latest, or error out? I'm fairly confident that just applying migration functions in order won't work because the database schema could have changed in some way that's incompatible with an outdated intermediate migration. So I think we should defer making a decision on this until the next time we need to migrate.

In terms of identifying which tenants need upgraded, I think the solution is to `alter table tenants add column provisioned_version integer not null default 0;`. The `agent` would define a code constant of `CURRENT_PROVISIONING_VERSION: i32`, which would be incremented whenever changes are made to the ops catalog. So it identifies tenants in need of update by querying for `tenants where provisioned_version < $CURRENT_PROVISIONING_VERSION`. And once a tenant is updated, it sets the `provisioned_version` to the `CURRENT_PROVISIONING_VERSION`.

Another question that arrises from those steps is whether the agent should continue to perform its normal operations while the tenant updates are in progress. If implemented naively, those steps would cause a deadlock because the agent can't process publications until after it has started up. We could resolve that be either:

- Make the tenant migrations happen asynchronously, and allow concurrent processing of publications.
- Make the tenant migrations synchronous, and synchronously process the publications.

I'm disqualifying the synchronous process because it makes the agent effectively unavailable while the migrations are running. This means that users may be unable to test, publish, etc. until after all tenant migrations have completed successfully (or we've rolled back the agent deployment). If we did it this way, it would push us toward doing deployments during off hours in order to minimize impact to users. The synchronous process would also require that we factor out a synchronous publish handler to use during the proces, and that's a little trickier that one might expect. For example, during a rolling deployment, we'd need to ensure that no _other_ agent process started processing the ops catalog publish (or else we might as well make it asynchronous).

The asyncronous process would allow the agent to remain available during the migration process, and I think this seems like the simplest approach all around. Concretely, this would mean that, on startup, the agent kicks off an asynchronous task that loops over all the tenants needing updated.

**Comment by jgraettinger** [comment]
> When the control-plane's database schema is changed (ex. add a column to the tenants table), it's not neccesarily clear whether it's better to update existing tenant rows as part of that same DB migration, versus re-running the (idempotent) betaOnboarding directive, versus having some other code-based migration.

This is an aside, but: we update tenant rows via an ALTER TABLE migration. We should _not_ re-run applied onboarding directives -- ever -- as they're a point-in-time application that's not semantically valid to run again.

Some comments:

 * Do we need versioning at all? Perhaps as a canary capability down the road, but at this moment, wouldn't we want everybody on the same version always? And given that the catalogs can be applied idempotently, an easy hammer is to apply the current version to all tenants regardless of what version they're on.

 * I do think we want to keep this process outside of the `agent` -- the agent has enough responsibility as it is, and this seems separable. With the exception of a raced beta-onboard directive application, why should the agent care that this process is running?

 * The biggest challenge, as I'm seeing it, is stats table migrations. I'd think we _cannot_ have tenants on different table versions in the general case because all `catalog_stats` partition tables must have shapes which are compatible with the `catalog_stats` table. So this process will presumably want to have one big schema transaction where it simultaneously updates the parent `catalog_stats` table and all tenant partitions thereof.
 
We may want to think of this as two discrete & manually-run scripts:
1) A DB migration which updates `catalog_stats` + tenant partitions schemas, and also removes materialization specs, done when the agent is scaled down and between releases, as we currently do other DB migrations. This is run only as part of a coordinated release, done by developers.
2) An online update of all tenant ops specs, which is done while the agent is running (and which the agent need not have specific awareness of). This can be run over and over again, by devs or operations / platform roles.
