### ISSUE TITLE
No stats created for new Task

### ISSUE THREAD

**Issue by dyaffe** [estuary/flow#877]
**Bug**
Materialization `estuary/test-market-data` is showing no data in the UI, though I can verify that data is being sync'd to snowflake.

I've verified that Supabase has no data for this in `catalog_stats`

**Comment by williamhbaker** [comment]
Currently the `ops/estuary/catalog-stats` shard is failed, which is responsible for read stats & logs collections and deriving those into the rolled-up stats documents that are materialized into `catalog_stats`.

It has failed due to a read of a log line that is not in compliance with the logs schema: It appears that older logs would emit documents with `"fields":null`, and the logs schema that the derivation is using has the `fields` field typed as `object`. I see in later log lines that `"fields":{}` is instead output, so this is probably from some logs that were written to the logs collection(s) prior to a previous change that took place quite a while ago.

One option would be to modify the logs schema (maybe a separate read schema?) so that the derivation could handle `fields` being `null` or an object. I don't think the actual derivation typescript using that property at all so it shouldn't be a huge lift.
